### ISSUE TITLE
出现rx.exceptions.OnErrorNotImplementedException

### ISSUE THREAD

**Issue by kolyneh** [wzgiceman/Rxbus#1]
在post事件时报错, 看了下应该是
   // 主题
    private final Subject bus;
这里没有泛型导致类型检查错误,然后没有onError处理导致异常
加上泛型后正常了 
private final Subject<Object, Object> bus;

**Comment by wzgiceman** [comment]
谢谢反馈，已经加入异常检测

**Comment by kolyneh** [comment]
#1回复少了"<>"

```
private final Subject<Object, Object> bus;
```
