### ISSUE TITLE
上传到jcenter,页面上没有Add to Jcenter按钮是咋回事？

### ISSUE THREAD

**Issue by RockyQu** [wzgiceman/Rxbus#5]
上传到jcenter,页面上没有Add to Jcenter按钮是咋回事？

**Comment by naivor** [comment]
我也遇到了，没有Add to jcenter

**Comment by RockyQu** [comment]
问题我知道在哪，你可能是注册了企业类型的账号，不是个人账号

**Comment by naivor** [comment]
嗯，是注册了trail 类型账号，已经变成普通账号了
